
name: deploy preview app
on:
  release:
    types: [ prereleased ]

jobs:
  deploy:
    name: Deploy Review app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "src"
        remoteDir: "preview"
